const assert = require('assert')
const demo = require('../data/demo')
assert.strictEqual(demo.trip.days,7)
assert.strictEqual(demo.trip.dayList.length,4)
assert.strictEqual(demo.events.filter(x=>x.day===2).length,5)
assert.strictEqual(demo.events.reduce((n,x)=>n+x.photos,0),155)
assert.ok(demo.events.every(x=>x.lat&&x.lng&&x.story&&x.period))
assert.deepStrictEqual([...new Set(demo.events.map(x=>x.id))].length,demo.events.length)
console.log('tests ok: demo domain model and Day 2 event flow')
